/* AUTO-GENERATED FILE - DO NOT EDIT */

export const repel = "data:image/webp;base64,UklGRrIAAABXRUJQVlA4TKUAAAAvFUAFELU4aiRJcjAtnaViCKZjCqayNHzNJZnATKkKQI9qjyehBob+uwx+KqhFBMNsJNUfYn+ncDqj0v8J6NlFkr02XrINgCOqnnMcx8GaCJAkIoqC9wNswIyCoGEAMM0oMA3bJumSW98EQJK+ih6eTZL2VSFtuSFJ/7WSFpoN5s+smqnZAL2BiZUm6RoZIK0qkbbKelzSGJJ0RS+NS8kremUkexYA" as const;

